### ISSUE TITLE
关于 my_public_ip

### ISSUE THREAD

**Issue by qiuzhangsaer** [cyoukon/auto_send_ip#2]
我是搞PHP的，家里nas需要监控一下公网变动使用了这个项目，代码里有些问题我在改，现在有个疑问，我不是很懂python，我想知道这个老ip是在哪里获取的，也没有看到my_public_ip在哪里取到值和新ip做比较啊

**Comment by cyoukon** [comment]
这是我很久前写的了，刚刚试了下，可以正常使用。
`main.py`的第15行开始，有`my_public_ip`与旧值的对比和取新值

**Comment by qiuzhangsaer** [comment]
> 这是我很久前写的了，刚刚试了下，可以正常使用。 `main.py`的第15行开始，有`my_public_ip`与旧值的对比和取新值

我知道，我的意思是这个旧值是如何获取的

**Comment by cyoukon** [comment]
程序起来后会获取一次ip并发送邮件，之后这个ip就算是旧值了。
程序入口点在`main.py`的第25行，你顺着那里往后看就好了
